/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthPhoneRouteImport } from './routes/auth/phone'
import { Route as AuthOtpRouteImport } from './routes/auth/otp'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated/products/index'
import { Route as AuthenticatedPacksIndexRouteImport } from './routes/_authenticated/packs/index'
import { Route as AuthenticatedOrdersIndexRouteImport } from './routes/_authenticated/orders/index'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers/index'
import { Route as AuthenticatedCategoriesIndexRouteImport } from './routes/_authenticated/categories/index'
import { Route as AuthenticatedAttributesIndexRouteImport } from './routes/_authenticated/attributes/index'
import { Route as AuthenticatedAdminsIndexRouteImport } from './routes/_authenticated/admins/index'
import { Route as AuthenticatedAdminsCreateRouteImport } from './routes/_authenticated/admins/create'
import { Route as AuthenticatedAdminsAdminIdRouteImport } from './routes/_authenticated/admins/$adminId'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthPhoneRoute = AuthPhoneRouteImport.update({
  id: '/phone',
  path: '/phone',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPacksIndexRoute = AuthenticatedPacksIndexRouteImport.update({
  id: '/packs/',
  path: '/packs/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersIndexRoute =
  AuthenticatedOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCategoriesIndexRoute =
  AuthenticatedCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttributesIndexRoute =
  AuthenticatedAttributesIndexRouteImport.update({
    id: '/attributes/',
    path: '/attributes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminsIndexRoute =
  AuthenticatedAdminsIndexRouteImport.update({
    id: '/admins/',
    path: '/admins/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminsCreateRoute =
  AuthenticatedAdminsCreateRouteImport.update({
    id: '/admins/create',
    path: '/admins/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminsAdminIdRoute =
  AuthenticatedAdminsAdminIdRouteImport.update({
    id: '/admins/$adminId',
    path: '/admins/$adminId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/otp': typeof AuthOtpRoute
  '/auth/phone': typeof AuthPhoneRoute
  '/auth/': typeof AuthIndexRoute
  '/admins/$adminId': typeof AuthenticatedAdminsAdminIdRoute
  '/admins/create': typeof AuthenticatedAdminsCreateRoute
  '/admins/': typeof AuthenticatedAdminsIndexRoute
  '/attributes/': typeof AuthenticatedAttributesIndexRoute
  '/categories/': typeof AuthenticatedCategoriesIndexRoute
  '/customers/': typeof AuthenticatedCustomersIndexRoute
  '/orders/': typeof AuthenticatedOrdersIndexRoute
  '/packs/': typeof AuthenticatedPacksIndexRoute
  '/products/': typeof AuthenticatedProductsIndexRoute
}
export interface FileRoutesByTo {
  '/auth/otp': typeof AuthOtpRoute
  '/auth/phone': typeof AuthPhoneRoute
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthIndexRoute
  '/admins/$adminId': typeof AuthenticatedAdminsAdminIdRoute
  '/admins/create': typeof AuthenticatedAdminsCreateRoute
  '/admins': typeof AuthenticatedAdminsIndexRoute
  '/attributes': typeof AuthenticatedAttributesIndexRoute
  '/categories': typeof AuthenticatedCategoriesIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/orders': typeof AuthenticatedOrdersIndexRoute
  '/packs': typeof AuthenticatedPacksIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/otp': typeof AuthOtpRoute
  '/auth/phone': typeof AuthPhoneRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_authenticated/admins/$adminId': typeof AuthenticatedAdminsAdminIdRoute
  '/_authenticated/admins/create': typeof AuthenticatedAdminsCreateRoute
  '/_authenticated/admins/': typeof AuthenticatedAdminsIndexRoute
  '/_authenticated/attributes/': typeof AuthenticatedAttributesIndexRoute
  '/_authenticated/categories/': typeof AuthenticatedCategoriesIndexRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/orders/': typeof AuthenticatedOrdersIndexRoute
  '/_authenticated/packs/': typeof AuthenticatedPacksIndexRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auth/otp'
    | '/auth/phone'
    | '/auth/'
    | '/admins/$adminId'
    | '/admins/create'
    | '/admins/'
    | '/attributes/'
    | '/categories/'
    | '/customers/'
    | '/orders/'
    | '/packs/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth/otp'
    | '/auth/phone'
    | '/'
    | '/auth'
    | '/admins/$adminId'
    | '/admins/create'
    | '/admins'
    | '/attributes'
    | '/categories'
    | '/customers'
    | '/orders'
    | '/packs'
    | '/products'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/auth/otp'
    | '/auth/phone'
    | '/_authenticated/'
    | '/auth/'
    | '/_authenticated/admins/$adminId'
    | '/_authenticated/admins/create'
    | '/_authenticated/admins/'
    | '/_authenticated/attributes/'
    | '/_authenticated/categories/'
    | '/_authenticated/customers/'
    | '/_authenticated/orders/'
    | '/_authenticated/packs/'
    | '/_authenticated/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/phone': {
      id: '/auth/phone'
      path: '/phone'
      fullPath: '/auth/phone'
      preLoaderRoute: typeof AuthPhoneRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/otp': {
      id: '/auth/otp'
      path: '/otp'
      fullPath: '/auth/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/packs/': {
      id: '/_authenticated/packs/'
      path: '/packs'
      fullPath: '/packs/'
      preLoaderRoute: typeof AuthenticatedPacksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/': {
      id: '/_authenticated/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthenticatedOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categories/': {
      id: '/_authenticated/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof AuthenticatedCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attributes/': {
      id: '/_authenticated/attributes/'
      path: '/attributes'
      fullPath: '/attributes/'
      preLoaderRoute: typeof AuthenticatedAttributesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admins/': {
      id: '/_authenticated/admins/'
      path: '/admins'
      fullPath: '/admins/'
      preLoaderRoute: typeof AuthenticatedAdminsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admins/create': {
      id: '/_authenticated/admins/create'
      path: '/admins/create'
      fullPath: '/admins/create'
      preLoaderRoute: typeof AuthenticatedAdminsCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admins/$adminId': {
      id: '/_authenticated/admins/$adminId'
      path: '/admins/$adminId'
      fullPath: '/admins/$adminId'
      preLoaderRoute: typeof AuthenticatedAdminsAdminIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminsAdminIdRoute: typeof AuthenticatedAdminsAdminIdRoute
  AuthenticatedAdminsCreateRoute: typeof AuthenticatedAdminsCreateRoute
  AuthenticatedAdminsIndexRoute: typeof AuthenticatedAdminsIndexRoute
  AuthenticatedAttributesIndexRoute: typeof AuthenticatedAttributesIndexRoute
  AuthenticatedCategoriesIndexRoute: typeof AuthenticatedCategoriesIndexRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
  AuthenticatedOrdersIndexRoute: typeof AuthenticatedOrdersIndexRoute
  AuthenticatedPacksIndexRoute: typeof AuthenticatedPacksIndexRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminsAdminIdRoute: AuthenticatedAdminsAdminIdRoute,
  AuthenticatedAdminsCreateRoute: AuthenticatedAdminsCreateRoute,
  AuthenticatedAdminsIndexRoute: AuthenticatedAdminsIndexRoute,
  AuthenticatedAttributesIndexRoute: AuthenticatedAttributesIndexRoute,
  AuthenticatedCategoriesIndexRoute: AuthenticatedCategoriesIndexRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  AuthenticatedOrdersIndexRoute: AuthenticatedOrdersIndexRoute,
  AuthenticatedPacksIndexRoute: AuthenticatedPacksIndexRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthOtpRoute: typeof AuthOtpRoute
  AuthPhoneRoute: typeof AuthPhoneRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthOtpRoute: AuthOtpRoute,
  AuthPhoneRoute: AuthPhoneRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
